name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run tests
        env:
          FLASHPOINT_API_KEY: dummy
          IPQS_API_KEY: dummy
          SPYCLOUD_API_ATO_KEY: dummy
          TWILIO_API_SID: dummy
          TWILIO_API_SECRET: dummy
          URLSCAN_API_KEY: dummy
          PYTHONPATH: .
        run: poetry run pytest --ignore=dev_env
